spring.application.name=ms-productos
server.port=${PORT:8080}

# Configuración de base de datos PostgreSQL
# spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ms-productos}
#spring.datasource.url=jdbc:postgresql://ep-broad-term-acapeodv-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
# spring.datasource.username=${DB_USERNAME:alexander}
# spring.datasource.password=${DB_PASSWORD:admin}

#postgresql://neondb_owner:npg_fSQX2lnYvr4o@ep-broad-term-acapeodv-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate y JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


key.signature=${JWT_SECRET}
app.message=${APP_MESSAGE: HOLA MUNDO}